language: node_js
node_js:
  - 'lts/*'

cache:
  directories:
    - 'node_modules'

# branches:
#   only:
#     - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local_dir: dist
  on:
    branch: master