language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: d0bc7cb363471a32151cc0f92a5bcdd1d34f995c
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master